<?php use App\Core\Csrf; use App\Core\View;
$youtubeId=''; if(!empty($item['youtube_url'])){$host=parse_url($item['youtube_url'],PHP_URL_HOST);$path=trim((string)parse_url($item['youtube_url'],PHP_URL_PATH),'/');$youtubeId=$host==='youtu.be'?$path:(string)(parse_url($item['youtube_url'],PHP_URL_QUERY)??'');if(str_contains($youtubeId,'v=')){parse_str($youtubeId,$q);$youtubeId=(string)($q['v']??'');}}
?>
<main class="invite <?= View::e($item['template_code']) ?> color-<?= View::e($item['color_preset']??'forest') ?> font-<?= View::e($item['font_preset']??'sans') ?> button-<?= View::e($item['button_preset']??'rounded') ?>"><header class="hero"><p class="church"><?= View::e($item['church_name']) ?></p><h1><?= View::e($item['title']) ?></h1><?php if($item['summary']): ?><p class="lead"><?= View::e($item['summary']) ?></p><?php endif; ?><?php if($item['hero_uuid']): ?><img class="hero-image" src="/media/<?= View::e($item['hero_uuid']) ?>" alt="" loading="eager"><?php endif; ?></header>
<section class="details"><?php if($item['event_at']): ?><div><span>일시</span><strong><?= View::e(date('Y년 n월 j일 H:i',strtotime($item['event_at']))) ?></strong></div><?php endif; ?><?php if($item['venue_name']): ?><div><span>장소</span><strong><?= View::e($item['venue_name']) ?></strong><small><?= View::e($item['venue_address']) ?></small></div><?php endif; ?></section>
<?php if($item['body']): ?><section class="body"><?= nl2br(View::e($item['body'])) ?></section><?php endif; ?>
<?php if (!empty($gallery)): ?><section class="gallery"><?php foreach ($gallery as $media): ?><img src="/media/<?= View::e($media['uuid']) ?>" width="<?= (int)$media['width'] ?>" height="<?= (int)$media['height'] ?>" alt="" loading="lazy"><?php endforeach; ?></section><?php endif; ?>
<?php if($youtubeId): ?><section class="video"><iframe src="https://www.youtube-nocookie.com/embed/<?= View::e($youtubeId) ?>" title="YouTube 영상" loading="lazy" allowfullscreen></iframe></section><?php endif; ?>
<div class="public-actions"><?php if($item['map_url']): ?><a href="<?= View::e($item['map_url']) ?>" target="_blank" rel="noopener">지도 보기</a><?php endif; ?><button type="button" id="share">초대장 공유</button></div>
<section id="apply" class="apply"><h2>참석 신청</h2><?php if($success): ?><div class="notice success"><?= View::e($success) ?></div><?php endif; ?><?php if($error): ?><div class="notice error"><?= View::e($error) ?></div><?php endif; ?>
<form method="post" action="/i/<?= View::e($item['church_slug']) ?>/<?= View::e($item['slug']) ?>/apply"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><label>이름<input name="applicant_name" required maxlength="100"></label><label>연락처<input name="phone" maxlength="30" inputmode="tel"></label><label>이메일<input type="email" name="email" maxlength="190"></label><label>참석 인원<input type="number" name="attendee_count" value="1" min="1" max="100"></label><label>메시지<textarea name="message" rows="3" maxlength="1000"></textarea></label>
<?php foreach($questions as $question): $answerName='answers['.(int)$question['id'].']'; $required=!empty($question['is_required']); $options=json_decode((string)($question['options_json']??'[]'),true); $options=is_array($options)?$options:[]; ?><label><?= View::e($question['label']) ?><?= $required?' *':'' ?><?php if($question['question_type']==='textarea'): ?><textarea name="<?= View::e($answerName) ?>" rows="3" maxlength="1000" <?= $required?'required':'' ?>></textarea><?php elseif($question['question_type']==='select'): ?><select name="<?= View::e($answerName) ?>" <?= $required?'required':'' ?>><option value="">선택해 주세요</option><?php foreach($options as $option): ?><option value="<?= View::e((string)$option) ?>"><?= View::e((string)$option) ?></option><?php endforeach; ?></select><?php elseif($question['question_type']==='checkbox'): ?><span class="check-option"><input type="checkbox" name="<?= View::e($answerName) ?>" value="1" <?= $required?'required':'' ?>> 확인</span><?php else: ?><input type="text" name="<?= View::e($answerName) ?>" maxlength="1000" <?= $required?'required':'' ?>><?php endif; ?></label><?php endforeach; ?>
<label class="consent"><input type="checkbox" name="privacy_consent" value="1" required> 신청 접수를 위한 개인정보 수집에 동의합니다.</label><button type="submit">신청하기</button></form></section>
<footer><?php if($item['contact_name']||$item['contact_phone']): ?>문의 <?= View::e($item['contact_name']) ?> <?= View::e($item['contact_phone']) ?><?php endif; ?></footer></main>
<script>document.getElementById('share')?.addEventListener('click',async()=>{const token='<?= View::e(Csrf::token()) ?>';fetch(location.pathname+'/share',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'_token='+encodeURIComponent(token)});if(navigator.share){await navigator.share({title:document.title,url:location.href});}else{await navigator.clipboard.writeText(location.href);alert('초대장 주소를 복사했습니다.');}});</script>
