$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$failures = [System.Collections.Generic.List[string]]::new()
$passes = 0
function Check([bool]$condition, [string]$message) {
    if ($condition) { $script:passes++; Write-Output "PASS $message" } else { $script:failures.Add($message); Write-Output "FAIL $message" }
}
function Read([string]$relative) { Get-Content -LiteralPath (Join-Path $root $relative) -Raw -Encoding utf8 }
$migration = Read 'database\migrations\202608310001_initial_identity.sql'
@('churches','users','platform_user_roles','platform_mfa_credentials','church_users','products','plans','plan_features','subscriptions','admin_audit_logs') | ForEach-Object { Check ($migration.Contains("CREATE TABLE $_")) "migration creates $_" }
$tenantRepo = Read 'app\Repositories\ChurchUserRepository.php'
Check ($tenantRepo.Contains('TenantContext $tenant')) 'tenant repository requires TenantContext'
Check ($tenantRepo.Contains('WHERE cu.church_id = :church_id')) 'tenant admin query scopes by church_id'
$churchRepo = Read 'app\Repositories\ChurchRepository.php'
Check ($churchRepo.Contains('id = :id AND id = :church_id')) 'tenant church query scopes by church_id'
$routes = Read 'routes\web.php'
Check ($routes.Contains('requirePlatform')) 'platform routes require platform authorization'
Check ($routes.Contains('requireTenant')) 'tenant routes require tenant authorization'
$auth = Read 'app\Core\Auth.php'
Check ($auth.Contains('password_verify')) 'login uses password_verify'
Check ($auth.Contains('Session::regenerate')) 'login regenerates session id'
Check ($auth.Contains('MFA_REQUIRED')) 'platform login requires MFA'
Check ($auth.Contains("`$pending['attempts'] >= 5")) 'MFA attempts are limited'
Check ((Read 'app\Repositories\MfaRepository.php').Contains('last_used_counter')) 'MFA prevents TOTP replay'
$service = Read 'app\Services\ChurchProvisioningService.php'
Check ($service.Contains('beginTransaction')) 'church provisioning is transactional'
Check ($service.Contains('password_hash')) 'admin passwords are hashed'
$trackedEnv = git -C $root ls-files -- .env
Check ([string]::IsNullOrWhiteSpace(($trackedEnv -join ''))) 'real .env is not tracked'
$mediaMigration = Read 'database\migrations\202609010003_media_management.sql'
Check ($mediaMigration.Contains('alt_text') -and $mediaMigration.Contains('usage_consent')) 'media migration adds accessibility and usage consent metadata'
Check ($mediaMigration.Contains('deleted_at') -and $mediaMigration.Contains('deleted_by')) 'media migration adds recoverable trash metadata'
$mediaRepo = Read 'app\Repositories\InvitationMediaRepository.php'
Check ($mediaRepo.Contains('listForTenant(TenantContext $tenant') -and $mediaRepo.Contains('m.church_id=:church_id')) 'media admin listing is tenant scoped'
Check ($mediaRepo.Contains('UPDATE invitation_media SET deleted_at=NOW()') -and $mediaRepo.Contains('restore(TenantContext $tenant')) 'media deletion uses recoverable trash and restore'
$mediaController = Read 'app\Controllers\MediaAdminController.php'
Check (($mediaController.Split('Csrf::verify').Count - 1) -ge 3) 'media mutations verify CSRF'
Check ($mediaController.Contains('media.metadata_updated') -and $mediaController.Contains('media.trashed') -and $mediaController.Contains('media.restored')) 'media mutations are audited'
Check ($routes.Contains("'/admin/media'") -and $routes.Contains("'/admin/storage'")) 'media and storage routes are registered'
Check ((Read 'resources\views\layout.php').Contains('/admin/media') -and (Read 'resources\views\layout.php').Contains('/admin/storage')) 'media and storage navigation is linked'
Check ((Read 'app\Services\InvitationImageService.php').Contains("'original_file_bytes'=>(int)(`$upload['size']??0)")) 'original upload byte size is retained as metadata'
$trafficController = Read 'app\Controllers\TrafficAdminController.php'
Check ($routes.Contains("'/admin/traffic'") -and (Read 'resources\views\layout.php').Contains('/admin/traffic')) 'tenant traffic detail is routed and linked'
Check ($trafficController.Contains('TenantContext::fromSession()') -and $trafficController.Contains('historyForTenant')) 'traffic detail derives tenant context and scoped request history'
Check ($trafficController.Contains('trafficExtraLimit($tenant)') -and $trafficController.Contains('max(0,$effective-$used)')) 'traffic detail presents base extra used and remaining limits'
Check ((Read 'app\Repositories\InvitationStatsRepository.php').Contains('dailyTrafficForTenant(TenantContext $tenant') -and (Read 'app\Repositories\InvitationStatsRepository.php').Contains('topTrafficInvitationsForTenant(TenantContext $tenant')) 'traffic detail queries require TenantContext'
$trafficView = Read 'resources\views\admin\traffic\index.php'
Check ($trafficView.Contains('action="/admin/quota-request"') -and -not $trafficView.Contains('action="/control/quota-requests/')) 'tenant traffic screen can only submit a platform-reviewed request'
$analyticsController = Read 'app\Controllers\AnalyticsAdminController.php'
Check ($routes.Contains("'/admin/analytics'") -and $routes.Contains("'/admin/analytics/export'") -and (Read 'resources\views\layout.php').Contains('/admin/analytics')) 'tenant analytics routes and navigation are linked'
Check ($analyticsController.Contains('TenantContext::fromSession()') -and $analyticsController.Contains('analytics.retention_days')) 'analytics is tenant scoped and retention limited'
Check ($analyticsController.Contains('analytics.exported') -and $analyticsController.Contains('preg_match') -and $analyticsController.Contains("fputcsv")) 'analytics CSV is audited and formula safe'
Check ((Read 'app\Repositories\InvitationStatsRepository.php').Contains('aggregateForTenant(TenantContext $tenant') -and (Read 'app\Repositories\InvitationStatsRepository.php').Contains('popularForTenant(TenantContext $tenant')) 'analytics queries require TenantContext'
Check ((Read 'app\Repositories\InvitationStatsRepository.php').Contains('periodAggregateForTenant(TenantContext $tenant') -and $analyticsController.Contains("'weekly'=>") -and $analyticsController.Contains("'monthly'=>")) 'weekly and monthly analytics are tenant scoped and bounded'
$questionRepo = Read 'app\Repositories\InvitationQuestionRepository.php'
$questionController = Read 'app\Controllers\QuestionAdminController.php'
$publicController = Read 'app\Controllers\PublicInvitationController.php'
$applicationRepo = Read 'app\Repositories\InvitationApplicationRepository.php'
$publicView = Read 'resources\views\public\invitation.php'
$eventView = Read 'resources\views\admin\events\index.php'
$eventController = Read 'app\Controllers\EventAdminController.php'
Check ($questionRepo.Contains('TenantContext $t') -and $questionRepo.Contains('church_id=:church_id') -and $questionRepo.Contains("SET is_active=0")) 'event questions are tenant scoped and deactivated without deletion'
Check ($questionController.Contains('Csrf::verify') -and $questionController.Contains("['owner','admin']") -and $questionController.Contains('event_question.saved')) 'question changes require management role CSRF and audit'
$publicQuestionAnswersSafe = ($publicController -match 'activePublic') -and ($applicationRepo -match 'JSON_THROW_ON_ERROR') -and ($publicController -match 'is_required')
Check $publicQuestionAnswersSafe 'public question answers are allowlisted validated and safely encoded'
Check ($publicView.Contains("answers[") -and $publicView.Contains("question_type']==='select'") -and $publicView.Contains("question_type']==='checkbox'")) 'public invitation renders supported question inputs'
Check ($eventView.Contains('/questions') -and $eventView.Contains('/attendance') -and $eventView.Contains('is_waitlisted')) 'event admin links questions and shows waitlist and attendance controls'
Check ($eventController.Contains('authorizeApplicantData($tenant)') -and $eventController.Contains('attendance_changed')) 'attendance changes restrict applicant data and write audit log'
$visibilityMigration=Read 'database\migrations\202609010005_invitation_visibility.sql';$publicInvitation=Read 'app\Controllers\PublicInvitationController.php';$invitationAdmin=Read 'app\Controllers\InvitationAdminController.php';$invitationRepo=Read 'app\Repositories\InvitationRepository.php'
Check ($visibilityMigration.Contains("ENUM('public','password','private')") -and $visibilityMigration.Contains('access_password_hash VARCHAR(255)')) 'visibility migration stores only password hashes'
Check ($invitationAdmin.Contains('password_hash') -and -not $invitationRepo.Contains('access_password ')) 'invitation access password is hashed and plaintext is not persisted'
Check ($publicInvitation.Contains('password_verify') -and $publicInvitation.Contains("visibility']==='private'") -and $publicInvitation.Contains('Response::abort(404')) 'password access verifies hashes and private invitations return 404'
Check (($publicInvitation.Split('requireVisibilityAccess').Count - 1) -ge 4) 'show apply and share require visibility access'
Check ($publicInvitation.Contains('$count>=5?time()+900:0')) 'password access limits five failures for fifteen minutes'
Check ($publicInvitation.Contains('INSERT INTO invitation_access_failures') -and $publicInvitation.Contains('invitation.access_failed')) 'password failures are stored and audited'
Check ($invitationRepo.Contains('i.publish_at <= NOW()') -and $invitationRepo.Contains('i.expires_at > NOW()')) 'visibility preserves scheduled publishing and expiry'
$mediaRepo=Read 'app\Repositories\InvitationMediaRepository.php'
Check ($mediaRepo.Contains('activeBelongsToInvitation(TenantContext $tenant') -and $mediaRepo.Contains('invitation_id=:invitation_id AND deleted_at IS NULL')) 'share media requires tenant invitation ownership and active state'
Check ($invitationAdmin.Contains("empty(`$existing['access_password_hash'])")) 'password visibility transition rejects a blank password without an existing hash'
$designMigration=Read 'database\migrations\202609010006_invitation_design.sql';$designController=Read 'app\Controllers\InvitationDesignController.php';$designView=Read 'resources\views\admin\invitation-design\index.php';$designCss=Read 'public\assets\design-presets.css'
Check ($designMigration.Contains('color_preset') -and $designMigration.Contains('font_preset') -and $designMigration.Contains('button_preset')) 'design migration adds controlled presets'
Check ($invitationRepo.Contains('updateDesign(TenantContext $tenant') -and $invitationRepo.Contains('id=:id AND church_id=:church_id')) 'design update is tenant scoped'
Check ($designController.Contains("['owner','admin']") -and $designController.Contains('Csrf::verify') -and $designController.Contains('invitation.design_updated')) 'design changes require role CSRF and audit'
Check ($designController.Contains('in_array') -and $designController.Contains('TEMPLATES') -and $designController.Contains('COLORS')) 'design preset input is allowlisted'
Check ($routes.Contains("'/admin/invitation-design'") -and (Read 'resources\views\layout.php').Contains('/admin/invitation-design')) 'design management is routed and linked'
Check ($publicView.Contains('color-') -and (Read 'resources\views\public\layout.php').Contains('design-presets.css')) 'public invitation applies design presets'
Check ($designView.Contains('1080') -and $designView.Contains('1200') -and $designCss.Contains('.design-preview')) 'design admin provides image guidance and preview styling'
$subscriptionRepo=Read 'app\Repositories\SubscriptionChangeRequestRepository.php';$platformController=Read 'app\Controllers\PlatformDashboardController.php';$subscriptionMigration=Read 'database\migrations\202608310007_subscription_management.sql'
Check ($subscriptionRepo.Contains('FOR UPDATE') -and $subscriptionRepo.Contains('beginTransaction') -and $subscriptionRepo.Contains('rollBack')) 'subscription completion is transactional and serialized'
Check ($subscriptionRepo.Contains("status']!=='awaiting_payment'") -and $subscriptionRepo.Contains('paymentReference') -and $subscriptionMigration.Contains('payment_confirmed_at')) 'subscription completion requires recorded payment confirmation'
Check ($subscriptionRepo.Contains("INSERT INTO subscriptions") -and $subscriptionRepo.Contains("status='completed'") -and $subscriptionRepo.Contains("UPDATE churches SET status='active'")) 'subscription completion applies plan and closes request'
Check ($routes.Contains('/subscription-requests/{id}/complete') -and $platformController.Contains('Csrf::verify') -and $platformController.Contains('subscription_change.completed')) 'subscription completion is platform protected CSRF verified and audited'
$trialRepo=Read 'app\Repositories\TrialManagementRepository.php';$trialCli=Read 'bin\expire-trials.php'
Check ($trialRepo.Contains('expireDue') -and $trialRepo.Contains("status='trialing'") -and $trialRepo.Contains('trial_ends_at<=NOW()')) 'trial expiry selects only due active trials'
Check ($trialRepo.Contains('FOR UPDATE') -and $trialRepo.Contains('beginTransaction') -and $trialRepo.Contains('rollBack')) 'trial auto expiry is serialized and transactional'
Check ($trialRepo.Contains('trial.auto_expired') -and $trialRepo.Contains('trial_operation_logs') -and -not $trialRepo.Contains('DELETE FROM')) 'trial auto expiry is audited without deleting data'
Check ($trialCli.Contains("PHP_SAPI !== 'cli'") -and $trialCli.Contains('FILTER_VALIDATE_INT') -and $trialCli.Contains('expireDue')) 'trial expiry CLI restricts execution and validates batch size'
$backup=Read 'bin\backup.sh';$restore=Read 'bin\restore-test.sh';$envExample=Read '.env.example'
Check ($backup.Contains('mysqldump') -and $backup.Contains('storage/uploads') -and $backup.Contains('single-transaction')) 'backup includes transactional database dump and uploads'
Check ($backup.Contains('aes-256-cbc') -and $backup.Contains('pbkdf2') -and $backup.Contains('sha256sum')) 'backup is encrypted and checksummed'
Check ($backup.IndexOf('tar -tzf') -lt $backup.IndexOf('-mtime +7') -and $backup.Contains('BACKUP_EXTERNAL_DIR')) 'retention runs only after verification in external storage'
Check ($restore.Contains('RESTORE_TEST_DB') -and $restore.Contains('Refusing to restore into the application database') -and $restore.Contains('sha256sum -c')) 'restore drill refuses production database and verifies checksum'
Check ($envExample.Contains('BACKUP_PASSPHRASE') -and $envExample.Contains('RESTORE_TEST_DB')) 'backup secrets and restore target use environment configuration'
$homeView=Read 'resources\views\home\index.php';$homeLayout=Read 'resources\views\home\layout.php';$homeCss=Read 'public\assets\home.css'
Check ($routes.Contains("View::render('home.index'") -and $routes.Contains("'home.layout'")) 'public root renders the landing page'
Check ($homeLayout.Contains('/assets/home.css') -and $homeCss.Contains('PretendardVariable.woff2')) 'landing page self-hosts Pretendard'
Check ($homeView.Contains('id="templates"') -and $homeView.Contains('id="features"') -and $homeView.Contains('id="pricing"')) 'landing page includes templates features and pricing'
Check ($homeCss.Contains('.js .reveal')) 'landing content remains visible without JavaScript'
Check (-not ($homeCss -match '[\x00-\x08\x0B\x0C\x0E-\x1F]') -and $homeCss.Contains('content:"\2713"')) 'landing CSS contains no parser-breaking control characters'
Check ($homeView.Contains('/assets/images/home/invitation-hero.webp') -and $homeView.Contains('/assets/images/home/community-preparation.webp') -and $homeView.Contains('/assets/images/home/youth-welcome.webp')) 'landing page links generated optimized imagery'
Check ((Test-Path (Join-Path $root 'public\assets\images\home\invitation-hero.webp')) -and (Test-Path (Join-Path $root 'public\assets\images\home\community-preparation.webp')) -and (Test-Path (Join-Path $root 'public\assets\images\home\youth-welcome.webp'))) 'landing generated imagery exists in public assets'
$templateView=Read 'resources\views\home\templates.php';$templateCss=Read 'public\assets\templates.css'
Check ($routes.Contains("$router->get('/templates'") -and $routes.Contains("View::render('home.templates'")) 'template catalog is publicly routed'
Check ($templateView.Contains('data-category') -and $templateView.Contains('orientation-filter') -and $templateView.Contains('template-catalog')) 'template catalog provides event and orientation filters'
Check ($templateView.Contains('preview-dialog') -and $templateView.Contains('data-preview') -and $templateView.Contains('showModal')) 'template catalog provides accessible mobile previews'
Check ($templateCss.Contains('@media(max-width:600px)') -and $templateCss.Contains('.template-catalog')) 'template catalog includes responsive styling'
$featureView=Read 'resources\views\home\features.php';$featureCss=Read 'public\assets\features.css'
Check ($routes.Contains("$router->get('/features'") -and $routes.Contains("View::render('home.features'")) 'feature detail page is publicly routed'
Check ($featureView.Contains("['01','design'") -and $featureView.Contains("['04','share'") -and $featureView.Contains("['05','apply'") -and $featureView.Contains("['07','insight'")) 'feature page explains design share application and insight flow'
Check ($featureView.Contains('trust-section') -and $featureView.Contains('SAFE & SIMPLE')) 'feature page communicates tenant isolation and privacy controls'
Check ($featureView.Contains('/assets/images/home/community-preparation.webp') -and $featureView.Contains('/assets/images/home/youth-welcome.webp')) 'feature page reuses optimized local imagery'
Check ($featureCss.Contains('@media(max-width:700px)') -and $featureCss.Contains('.feature-detail') -and -not ($featureCss -match '[\x00-\x08\x0B\x0C\x0E-\x1F]')) 'feature page has responsive parser-safe styling'
Check ($homeView.Contains('href="/features"') -and $templateView.Contains('href="/features"')) 'landing and template pages link the feature detail page'
$pricingView=Read 'resources\views\home\pricing.php';$pricingCss=Read 'public\assets\pricing.css'
Check ($routes.Contains("$router->get('/pricing'") -and $routes.Contains("View::render('home.pricing'")) 'pricing page is publicly routed'
Check ($pricingView.Contains("['trial'") -and $pricingView.Contains("['basic'") -and $pricingView.Contains("['growth'")) 'pricing page presents the three invitation product families'
Check ($pricingView.Contains('70%') -and $pricingView.Contains('85%') -and $pricingView.Contains('100%')) 'pricing page presents usage thresholds'
Check ($pricingCss.Contains('@media(max-width:600px)') -and $homeView.Contains('href="/pricing"') -and $featureView.Contains('href="/pricing"') -and $templateView.Contains('href="/pricing"')) 'public pages link a responsive pricing page'
if ($failures.Count -gt 0) { throw "$($failures.Count) contract test(s) failed: $($failures -join ', ')" }
Write-Output "OK $passes contract tests passed."
