<?php use App\Core\View;
$limit=static fn($code)=>(int)($subscription['features'][$code]['limit']??0);
$pct=static fn($used,$max)=>$max>0?min(100,round($used/$max*100)):0;
?>
<div class="page-header"><div><p class="eyebrow">전도지·초대장 관리자</p><h1><?= View::e($church['name']) ?></h1><p class="muted"><?= View::e($subscription['plan_name']) ?> · <?= View::e($subscription['status']) ?><?php if($subscription['trial_ends_at']): ?> · 체험 종료 <?= View::e($subscription['trial_ends_at']) ?><?php endif; ?></p></div><a class="button primary" href="/admin/invitations/create">초대장 만들기</a></div>
<div class="cards"><article class="card"><span>전체 초대장</span><strong><?= count($items) ?></strong></article><article class="card"><span>게시 중</span><strong><?= count(array_filter($items,fn($i)=>$i['status']==='published')) ?> / <?= number_format($limit('invitation.active_count')) ?></strong></article><article class="card"><span>누적 조회</span><strong><?= number_format((int)$usage['views']) ?></strong></article><article class="card"><span>누적 신청</span><strong><?= number_format((int)$usage['applications']) ?></strong></article></div>
<section class="panel"><div class="section-head"><h2>이번 달 사용량</h2><a href="/admin/invitations">초대장 관리</a></div>
<div class="meter-row"><div><strong>트래픽</strong><span><?= number_format($usage['traffic_bytes']/1048576,1) ?>MB / <?= number_format($limit('traffic.monthly_bytes')/1073741824,1) ?>GB</span></div><progress max="100" value="<?= $pct($usage['traffic_bytes'],$limit('traffic.monthly_bytes')) ?>"></progress></div>
<div class="meter-row"><div><strong>저장 용량</strong><span><?= number_format($usage['storage_bytes']/1048576,1) ?>MB / <?= number_format($limit('storage.total_bytes')/1048576,0) ?>MB</span></div><progress max="100" value="<?= $pct($usage['storage_bytes'],$limit('storage.total_bytes')) ?>"></progress></div></section>
<section class="panel"><h2>최근 초대장</h2><div class="table-wrap"><table><thead><tr><th>제목</th><th>상태</th><th>조회</th><th>신청</th></tr></thead><tbody><?php foreach(array_slice($items,0,5) as $i): ?><tr><td><a href="/admin/invitations/<?= (int)$i['id'] ?>/edit"><?= View::e($i['title']) ?></a></td><td><?= View::e($i['status']) ?></td><td><?= number_format((int)$i['views']) ?></td><td><?= number_format((int)$i['application_count']) ?></td></tr><?php endforeach; ?><?php if($items===[]): ?><tr><td colspan="4" class="empty">첫 초대장을 만들어 보세요.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel"><h2>관리자 계정</h2><p><?= count($admins) ?> / <?= number_format($limit('admin.max_count')) ?>개 사용 중</p></section>

