<?php use App\Core\View;
$limit=static fn($code)=>(int)($subscription['features'][$code]['limit']??0);
$pct=static fn($used,$max)=>$max>0?min(100,round($used/$max*100)):0;
?>
<div class="page-header"><div><p class="eyebrow">전도지·초대장 관리자</p><h1><?= View::e($church['name']) ?></h1><p class="muted"><?= View::e($subscription['plan_name']) ?> · <?= View::e($subscription['status']) ?><?php if($subscription['trial_ends_at']): ?> · 체험 종료 <?= View::e($subscription['trial_ends_at']) ?><?php endif; ?></p></div><a class="button primary" href="/admin/invitations/create">초대장 만들기</a></div>
<div class="cards"><article class="card"><span>전체 초대장</span><strong><?= count($items) ?></strong></article><article class="card"><span>게시 중</span><strong><?= count(array_filter($items,fn($i)=>$i['status']==='published')) ?> / <?= number_format($limit('invitation.active_count')) ?></strong></article><article class="card"><span>누적 조회</span><strong><?= number_format((int)$usage['views']) ?></strong></article><article class="card"><span>누적 신청</span><strong><?= number_format((int)$usage['applications']) ?></strong></article></div>
<section class="panel"><div class="section-head"><div><h2>관리 설정 진행도</h2><p class="muted">초대장 운영에 필요한 기본 설정입니다.</p></div><strong class="setup-score"><?= $setupPercent ?>%</strong></div><progress class="setup-progress" max="100" value="<?= $setupPercent ?>"></progress><ul class="setup-list"><?php foreach($setupChecklist as $step): ?><li class="<?= $step['done']?'done':'' ?>"><span aria-hidden="true"><?= $step['done']?'✓':'○' ?></span><?= View::e($step['label']) ?></li><?php endforeach; ?></ul><?php if($setupPercent<100 && in_array($tenant->role(),['owner','admin'],true)): ?><a class="button secondary" href="/admin/church">기본정보 설정하기</a><?php endif; ?></section>
<section class="panel"><div class="section-head"><h2>이번 달 사용량</h2><a href="/admin/invitations">초대장 관리</a></div>
<div class="meter-row"><div><strong>트래픽</strong><span><?= number_format($usage['traffic_bytes']/1048576,1) ?>MB / <?= number_format($limit('traffic.monthly_bytes')/1073741824,1) ?>GB</span></div><progress class="traffic-<?= View::e($trafficLevel) ?>" max="100" value="<?= $pct($usage['traffic_bytes'],$limit('traffic.monthly_bytes')) ?>"></progress></div>
<?php if($trafficLevel!=='normal'): ?><div class="alert <?= $trafficLevel==='warning'?'alert-warning':'alert-error' ?>"><?php if($trafficLevel==='blocked'): ?>월 트래픽을 모두 사용해 신규 이미지 업로드가 제한됩니다.<?php elseif($trafficLevel==='danger'): ?>월 트래픽의 85% 이상을 사용했습니다. 요금제 상향 또는 증액을 준비해 주세요.<?php else: ?>월 트래픽의 70% 이상을 사용했습니다. 사용량을 확인해 주세요.<?php endif; ?></div><?php endif; ?>
<p class="muted">다음 자동 초기화: <?= View::e($trafficResetsAt) ?> · 지난 사용량은 월별 통계로 보존됩니다.</p>
<?php if($trafficHistory!==[]): ?><details class="usage-history"><summary>최근 월별 트래픽 보기</summary><table><thead><tr><th>월</th><th>사용량</th></tr></thead><tbody><?php foreach($trafficHistory as $month): ?><tr><td><?= View::e($month['usage_month']) ?></td><td><?= number_format((int)$month['traffic_bytes']/1048576,1) ?>MB</td></tr><?php endforeach; ?></tbody></table></details><?php endif; ?>
<div class="meter-row"><div><strong>저장 용량</strong><span><?= number_format($usage['storage_bytes']/1048576,1) ?>MB / <?= number_format($limit('storage.total_bytes')/1048576,0) ?>MB</span></div><progress max="100" value="<?= $pct($usage['storage_bytes'],$limit('storage.total_bytes')) ?>"></progress></div></section>
<section class="panel"><h2>트래픽 초기화·증액 요청</h2><p class="muted">요청은 즉시 적용되지 않으며 플랫폼 운영자의 확인과 승인이 필요합니다.</p><?php if($message=\App\Core\Session::pullFlash('success')): ?><div class="alert alert-success"><?= View::e($message) ?></div><?php endif; ?><?php if($message=\App\Core\Session::pullFlash('error')): ?><div class="alert alert-error"><?= View::e($message) ?></div><?php endif; ?><?php if(in_array($tenant->role(),['owner','admin'],true)): ?><form method="post" action="/admin/quota-request" class="quota-request-form"><input type="hidden" name="_token" value="<?= View::e(\App\Core\Csrf::token()) ?>"><label>요청 유형<select name="request_type" required><option value="traffic_increase">트래픽 증액</option><option value="traffic_reset">이번 달 트래픽 초기화</option></select></label><label>증액 용량(GB)<input type="number" name="requested_gb" min="1" max="1000" value="1"></label><label>요청 사유<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><button class="button secondary" type="submit">승인 요청하기</button></form><?php endif; ?><?php if($quotaRequests!==[]): ?><h3>처리 대기 요청</h3><div class="table-wrap"><table><thead><tr><th>유형</th><th>요청량</th><th>사유</th><th>요청일</th></tr></thead><tbody><?php foreach($quotaRequests as $request): ?><tr><td><?= $request['request_type']==='traffic_reset'?'초기화':'증액' ?></td><td><?= $request['requested_bytes']?number_format((int)$request['requested_bytes']/1073741824).'GB':'-' ?></td><td><?= View::e($request['reason']) ?></td><td><?= View::e($request['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><section class="panel"><h2>최근 초대장</h2><div class="table-wrap"><table><thead><tr><th>제목</th><th>상태</th><th>조회</th><th>신청</th></tr></thead><tbody><?php foreach(array_slice($items,0,5) as $i): ?><tr><td><a href="/admin/invitations/<?= (int)$i['id'] ?>/edit"><?= View::e($i['title']) ?></a></td><td><?= View::e($i['status']) ?></td><td><?= number_format((int)$i['views']) ?></td><td><?= number_format((int)$i['application_count']) ?></td></tr><?php endforeach; ?><?php if($items===[]): ?><tr><td colspan="4" class="empty">첫 초대장을 만들어 보세요.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel"><h2>관리자 계정</h2><p><?= count($admins) ?> / <?= number_format($limit('admin.max_count')) ?>개 사용 중</p></section>

