<?php
use App\Core\View;
$features=$subscription['features'];
$limit=static fn(string $code):?int=>isset($features[$code])?$features[$code]['limit']:null;
$labels=['invitation.active_count'=>'활성 초대장','invitation.monthly_create_count'=>'월 초대장 생성','invitation.photos_per_item'=>'초대장당 사진','application.max_count'=>'신청자','traffic.monthly_bytes'=>'월 트래픽','storage.total_bytes'=>'저장공간','admin.max_count'=>'관리자','analytics.retention_days'=>'통계 보관'];
$formatLimit=static function(string $code,?int $value):string{if($value===null)return '제한 없음';if($code==='traffic.monthly_bytes')return number_format($value/1073741824,1).'GB';if($code==='storage.total_bytes')return number_format($value/1048576).'MB';if($code==='analytics.retention_days')return number_format($value).'일';return number_format($value).'개';};
$statusLabels=['trialing'=>'무료 체험','active'=>'이용 중','past_due'=>'결제 확인 필요','suspended'=>'이용 정지','cancelled'=>'해지','expired'=>'만료'];
$requestLabels=['traffic_increase'=>'트래픽 증액','traffic_reset'=>'트래픽 초기화'];$requestStatus=['pending'=>'처리 대기','approved'=>'승인','rejected'=>'반려'];
?>
<div class="page-header"><div><p class="eyebrow">구독·결제</p><h1>구독 및 사용 한도</h1><p class="muted">요금제 이름이 아닌 기능별 권한과 한도를 기준으로 적용합니다.</p></div><a class="button secondary" href="/admin#quota">한도 변경 요청</a></div>
<?php if(!empty($success)): ?><div class="notice success"><?= View::e($success) ?></div><?php endif; ?>
<?php if(!empty($error)): ?><div class="notice danger"><?= View::e($error) ?></div><?php endif; ?>
<div class="cards"><article class="card"><span>현재 상품</span><strong><?= View::e($subscription['plan_name']) ?></strong></article><article class="card"><span>상태</span><strong><?= View::e($statusLabels[$subscription['status']]??$subscription['status']) ?></strong></article><article class="card"><span>현재 이용 기간</span><strong class="period-value"><?= View::e(substr((string)$subscription['period_ends_at'],0,10)) ?>까지</strong></article></div>
<?php if($subscription['status']==='expired'): ?><div class="alert alert-error">구독이 만료되어 새 콘텐츠 생성과 변경이 제한됩니다. 플랫폼 운영자에게 전환을 요청해 주세요.</div><?php elseif($subscription['status']==='trialing'): ?><div class="alert alert-warning">무료 체험은 <?= View::e(substr((string)$subscription['trial_ends_at'],0,10)) ?>에 종료됩니다. 데이터는 유료 전환 후에도 유지됩니다.</div><?php endif; ?>
<section class="panel"><h2>기능별 한도</h2><div class="table-wrap"><table><thead><tr><th>기능</th><th>제공 한도</th><th>현재 사용</th></tr></thead><tbody><?php foreach($labels as $code=>$label): $value=$limit($code); ?><tr><td><?= View::e($label) ?></td><td><?= View::e($formatLimit($code,$value)) ?></td><td><?php if($code==='traffic.monthly_bytes'): ?><?= number_format((int)$usage['traffic_bytes']/1048576,1) ?>MB<?php elseif($code==='storage.total_bytes'): ?><?= number_format((int)$usage['storage_bytes']/1048576,1) ?>MB<?php else: ?>-<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><p class="muted">플랫폼 운영자가 승인한 추가 한도는 위 제공 한도에 합산되어 표시됩니다.</p></section>
<section class="panel"><h2>한도 변경 요청 이력</h2><div class="table-wrap"><table><thead><tr><th>요청</th><th>용량</th><th>상태</th><th>요청일</th><th>처리 메모</th></tr></thead><tbody><?php foreach($requests as $request): ?><tr><td><?= View::e($requestLabels[$request['request_type']]??$request['request_type']) ?></td><td><?= $request['requested_bytes']!==null?number_format((int)$request['requested_bytes']/1073741824).'GB':'-' ?></td><td><span class="badge badge-<?= View::e($request['status']) ?>"><?= View::e($requestStatus[$request['status']]??$request['status']) ?></span></td><td><?= View::e($request['created_at']) ?></td><td><?= View::e($request['review_note']??'-') ?></td></tr><?php endforeach; ?><?php if($requests===[]): ?><tr><td colspan="5" class="empty">한도 변경 요청 이력이 없습니다.</td></tr><?php endif; ?></tbody></table></div></section>

<section class="panel"><h2>유료 상품 전환 요청</h2><p class="muted">요청과 플랫폼 검토만 접수됩니다. 결제가 확인되기 전에는 현재 구독과 한도가 변경되지 않습니다.</p>
<?php if($canRequestChange): ?><form method="post" action="/admin/subscription/change-request" class="form-grid"><input type="hidden" name="_token" value="<?= View::e(\App\Core\Csrf::token()) ?>"><label>요청 상품<select name="plan_id" required><option value="">선택</option><?php foreach($plans as $plan): ?><option value="<?= (int)$plan['id'] ?>"><?= View::e($plan['name']) ?> · 월 <?= number_format((int)$plan['price_krw']) ?>원</option><?php endforeach; ?></select></label><label class="full">요청 메모<textarea name="reason" maxlength="500" rows="3" placeholder="전환 목적이나 문의사항을 입력해 주세요."></textarea></label><div class="full"><button class="button primary" type="submit">유료 전환 검토 요청</button></div></form><?php else: ?><p>대표 관리자 또는 관리자만 전환을 요청할 수 있습니다.</p><?php endif; ?>
<div class="table-wrap"><table><thead><tr><th>상품</th><th>월 금액</th><th>상태</th><th>요청일</th><th>검토 메모</th></tr></thead><tbody><?php $changeStatus=['pending'=>'검토 대기','awaiting_payment'=>'결제 확인 대기','completed'=>'전환 완료','rejected'=>'반려','cancelled'=>'취소']; foreach($changeRequests as $request): ?><tr><td><?= View::e($request['plan_name']) ?></td><td><?= number_format((int)$request['price_krw']) ?>원</td><td><?= View::e($changeStatus[$request['status']]??$request['status']) ?></td><td><?= View::e($request['created_at']) ?></td><td><?= View::e($request['review_note']??'-') ?></td></tr><?php endforeach; ?><?php if($changeRequests===[]): ?><tr><td colspan="5" class="empty">유료 전환 요청 이력이 없습니다.</td></tr><?php endif; ?></tbody></table></div></section>
