<?php use App\Core\Csrf; use App\Core\View; $v=static fn(string $key,string $default='')=>View::e($item[$key]??$default); ?>
<div class="page-header"><div><p class="eyebrow">초대장 편집</p><h1><?= View::e($title) ?></h1><p class="muted">영상은 업로드하지 않고 YouTube 링크만 입력합니다.</p></div><a class="button secondary" href="/admin/invitations">목록</a></div>
<?php if ($error): ?><div class="alert alert-error"><?= View::e($error) ?></div><?php endif; ?><?php if (!empty($success)): ?><div class="alert alert-success"><?= View::e($success) ?></div><?php endif; ?>
<form method="post" action="<?= View::e($action) ?>" class="panel form-grid" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>">
<h2>기본 정보</h2>
<label>제목<input name="title" required maxlength="150" value="<?= $v('title') ?>" placeholder="새가족 초청예배"></label>
<label>공개 주소<input name="slug" required pattern="[a-z0-9][a-z0-9-]{2,79}" value="<?= $v('slug') ?>" placeholder="welcome-2026"><small>영문 소문자·숫자·하이픈만 사용</small></label>
<label>행사 유형<select name="event_type"><?php foreach(['worship'=>'예배','evangelism'=>'전도·초청','conference'=>'집회·세미나','education'=>'교육','volunteer'=>'봉사','community'=>'교제·공동체','other'=>'기타'] as $k=>$label): ?><option value="<?= $k ?>" <?= ($item['event_type']??'worship')===$k?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label>모바일 디자인<select name="template_code"><?php foreach(['portrait'=>'세로형','square'=>'정사각형','landscape'=>'가로형'] as $k=>$label): ?><option value="<?= $k ?>" <?= ($item['template_code']??'portrait')===$k?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label>공개 방식<select name="visibility"><?php foreach(['public'=>'공개','password'=>'비밀번호','private'=>'비공개'] as $k=>$label):?><option value="<?=$k?>" <?=($item['visibility']??'public')===$k?'selected':''?>><?=$label?></option><?php endforeach?></select></label><label>접근 비밀번호<input type="password" name="access_password" minlength="8" autocomplete="new-password" placeholder="수정 시 비워두면 기존 비밀번호 유지"></label><label>공유 이미지 미디어 ID<input type="number" name="share_media_id" min="0" value="<?=View::e($item['share_media_id']??0)?>"><small>현재 교회의 업로드 이미지 ID만 사용할 수 있습니다.</small></label>
<label class="full">한 줄 소개<input name="summary" maxlength="255" value="<?= $v('summary') ?>" placeholder="당신을 특별한 예배에 초대합니다."></label>
<label class="full">상세 내용<textarea name="body" rows="8" maxlength="10000"><?= $v('body') ?></textarea></label>
<h2>일정과 장소</h2>
<label>행사 일시<input type="datetime-local" name="event_at" value="<?= $v('event_at') ? View::e(str_replace(' ','T',substr((string)($item['event_at']??''),0,16))) : '' ?>"></label>
<label>접수 시작<input type="datetime-local" name="registration_starts_at" value="<?= $v('registration_starts_at') ? View::e(str_replace(' ','T',substr((string)($item['registration_starts_at']??''),0,16))) : '' ?>"></label><label>접수 종료<input type="datetime-local" name="registration_ends_at" value="<?= $v('registration_ends_at') ? View::e(str_replace(' ','T',substr((string)($item['registration_ends_at']??''),0,16))) : '' ?>"></label><label>정원 (0은 제한 없음)<input type="number" name="capacity" min="0" max="100000" value="<?= View::e($item['capacity']??0) ?>"></label><label><input type="checkbox" name="waitlist_enabled" value="1" <?= !empty($item['waitlist_enabled'])?'checked':'' ?>> 정원 초과 시 대기자로 접수</label>
<label>예약 게시<input type="datetime-local" name="publish_at" value="<?= $v('publish_at') ? View::e(str_replace(' ','T',substr((string)($item['publish_at']??''),0,16))) : '' ?>"><small>비워두면 게시 버튼을 누르는 즉시 공개됩니다.</small></label>
<label>공개 만료<input type="datetime-local" name="expires_at" value="<?= $v('expires_at') ? View::e(str_replace(' ','T',substr((string)($item['expires_at']??''),0,16))) : '' ?>"><small>예약 게시보다 늦어야 하며, 만료 뒤 공개 주소는 자동 차단됩니다.</small></label>
<label>장소명<input name="venue_name" maxlength="150" value="<?= $v('venue_name') ?>"></label>
<label class="full">주소<input name="venue_address" maxlength="255" value="<?= $v('venue_address') ?>"></label>
<label class="full">지도 링크<input type="url" name="map_url" maxlength="500" value="<?= $v('map_url') ?>" placeholder="https://..."></label>
<h2>미디어와 문의</h2><label class="full">대표 이미지<input type="file" name="hero_image" accept="image/jpeg,image/png,image/webp"><small>JPG·PNG·WebP, 원본 최대 1MB. 업로드 시 최대 1080×1350 WebP로 자동 최적화됩니다.</small></label>
<label class="full">갤러리 이미지<input type="file" name="gallery_images[]" accept="image/jpeg,image/png,image/webp" multiple><small>여러 장 선택 가능, 장당 원본 최대 1MB. 초대장당 사진 수와 전체 저장공간 한도가 적용됩니다.</small></label>
<?php if (!empty($gallery)): ?><div class="full media-grid"><?php foreach ($gallery as $media): ?><div class="media-card"><img src="/media/<?= View::e($media['uuid']) ?>" alt="등록된 초대장 사진" loading="lazy"><form method="post" action="/admin/invitations/<?= (int)$item['id'] ?>/media/<?= (int)$media['id'] ?>/delete" onsubmit="return confirm('이 사진을 삭제할까요?')"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="danger small" type="submit">사진 삭제</button></form></div><?php endforeach; ?></div><?php endif; ?>
<label class="full">YouTube 링크<input type="url" name="youtube_url" maxlength="500" value="<?= $v('youtube_url') ?>" placeholder="https://youtu.be/..."></label>
<label>문의 담당자<input name="contact_name" maxlength="100" value="<?= $v('contact_name') ?>"></label>
<label>문의 전화<input name="contact_phone" maxlength="30" value="<?= $v('contact_phone') ?>"></label>
<div class="form-actions"><button class="primary" type="submit"><?= $editing?'변경사항 저장':'초대장 임시저장' ?></button><?php if($editing): ?><a class="button secondary" target="_blank" href="/admin/invitations">게시 상태 확인</a><?php endif; ?></div>
</form>
