<?php use App\Core\Csrf;use App\Core\View;$mb=static fn($b)=>number_format(((int)$b)/1048576,1).' MB';$gb=static fn($b)=>number_format(((int)$b)/1073741824,2).' GB'; ?>
<div class="page-header"><div><div class="eyebrow">Traffic usage</div><h1>트래픽 상세</h1><p class="muted">현재 구독 주기의 전송량과 승인 요청 이력을 확인합니다.</p></div></div>
<?php if($success):?><div class="alert alert-success"><?=View::e($success)?></div><?php endif?><?php if($error):?><div class="alert alert-error"><?=View::e($error)?></div><?php endif?>
<div class="cards"><div class="card"><span>기본 한도</span><strong><?=$gb($base)?></strong></div><div class="card"><span>추가 한도</span><strong><?=$gb($extra)?></strong></div><div class="card"><span>사용</span><strong><?=$gb($used)?></strong></div><div class="card"><span>잔여</span><strong><?=$gb($remaining)?></strong></div></div>
<section class="panel"><h2>현재 주기</h2><div class="meter-row"><div><strong><?=View::e($snapshot['period_starts_at']??date('Y-m-01'))?> ~ <?=View::e($snapshot['period_ends_at']??$nextReset)?></strong><span><?=$percent?>%</span></div><progress class="traffic-<?=View::e($level)?>" max="100" value="<?=min(100,$percent)?>"></progress></div><p>다음 자동 초기화: <strong><?=View::e($nextReset)?></strong></p><div class="alert alert-warning">70% 안내 · 85% 경고 및 증액/상향 안내 · 100% 신규 대용량 업로드 제한. 핵심 정적 정보는 가능한 계속 제공합니다.</div></section>
<section class="panel"><h2>초기화·증액 승인 요청</h2><p class="muted">관리자가 직접 사용량이나 한도를 변경할 수 없습니다. 플랫폼 운영자 승인 후 반영됩니다.</p><?php if(in_array($tenant->role(),['owner','admin'],true)):?><form method="post" action="/admin/quota-request" class="form-grid"><input type="hidden" name="_token" value="<?=View::e(Csrf::token())?>"><label>유형<select name="request_type"><option value="traffic_increase">트래픽 증액</option><option value="traffic_reset">이번 달 초기화</option></select></label><label>증액 GB<input type="number" name="requested_gb" min="1" max="1000" value="1"></label><label class="full">사유<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><div class="form-actions"><button class="secondary">플랫폼 승인 요청</button></div></form><?php endif?></section>
<section class="panel"><h2>최근 일별 사용량</h2><div class="table-wrap"><table><thead><tr><th>날짜</th><th>전송량</th></tr></thead><tbody><?php foreach($daily as $r):?><tr><td><?=View::e($r['stat_date'])?></td><td><?=$mb($r['traffic_bytes'])?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><h2>월별 사용량</h2><div class="table-wrap"><table><thead><tr><th>월</th><th>전송량</th></tr></thead><tbody><?php foreach($monthly as $r):?><tr><td><?=View::e($r['usage_month'])?></td><td><?=$gb($r['traffic_bytes'])?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><h2>이번 달 고사용 초대장·미디어</h2><p class="muted">현재 통계는 초대장 단위로 전송량을 집계하며 연결된 활성 미디어 수와 저장량을 함께 표시합니다.</p><div class="table-wrap"><table><thead><tr><th>초대장</th><th>트래픽</th><th>미디어</th><th>미디어 저장량</th></tr></thead><tbody><?php foreach($top as $r):?><tr><td><a href="/admin/invitations/<?=$r['id']?>/stats"><?=View::e($r['title'])?></a></td><td><?=$mb($r['traffic_bytes'])?></td><td><?=number_format((int)$r['media_count'])?>개</td><td><?=$mb($r['media_bytes'])?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><h2>요청 처리 이력</h2><div class="table-wrap"><table><thead><tr><th>유형</th><th>요청량</th><th>상태</th><th>요청일</th><th>처리일</th></tr></thead><tbody><?php foreach($requests as $r):?><tr><td><?=$r['request_type']==='traffic_reset'?'초기화':'증액'?></td><td><?=$r['requested_bytes']?$gb($r['requested_bytes']):'-'?></td><td><?=View::e($r['status'])?></td><td><?=View::e($r['created_at'])?></td><td><?=View::e($r['reviewed_at']??'-')?></td></tr><?php endforeach?></tbody></table></div></section>
