<?php
use App\Core\View;
$dashboardUrl=isset($dashboardUrl)&&is_string($dashboardUrl)?$dashboardUrl:null;
$loginUrl=$dashboardUrl??'/login';
$samples=[['새생명축제','당신을 위한 따뜻한 초대','green','NEW LIFE'],['부활절 감사예배','다시, 생명의 기쁨으로','cream','EASTER'],['청년 찬양집회','우리의 노래가 예배가 되는 밤','blue','WORSHIP'],['여름 수련회','믿음 안에서 함께 자라요','orange','RETREAT'],['성탄절 초청예배','기쁨의 소식을 함께 나눠요','red','CHRISTMAS']];
$functions=[['01','행사에 맞는 디자인','절기예배부터 수련회까지 교회 행사에 어울리는 화면을 선택합니다.'],['02','사진과 영상으로 풍성하게','교회 사진과 YouTube 영상으로 행사 분위기를 생생하게 전합니다.'],['03','행사 정보를 한 번에','일시, 장소, 지도와 문의처를 한 화면에서 정확하게 안내합니다.'],['04','간편한 참석 신청','방문자는 모바일에서 신청하고 관리자는 신청자를 확인합니다.'],['05','링크와 QR로 공유','문자, 메신저, 주보와 현수막 어디서든 초대장을 나눕니다.'],['06','방문과 공유 현황','조회, 공유, 신청 흐름을 확인해 다음 초청을 준비합니다.']];
?>
<header class="site-header"><a class="brand" href="/"><b>✦</b><span>Church Invitation</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">메뉴</button><nav id="main-nav"><a href="#templates">초대장 예시</a><a href="#features">주요 기능</a><a href="#steps">이용 방법</a><a href="#pricing">요금 안내</a></nav><a class="login-link" href="<?=View::e($loginUrl)?>"><?=$dashboardUrl?'관리자 화면':'로그인'?></a></header>
<main>
<section class="hero">
 <div class="hero-copy reveal"><p class="eyebrow"><i></i>마음을 잇는 기독교 모바일 초대장</p><h1>기쁜 소식을<br><em>가장 따뜻하게</em><br>전해보세요.</h1><p>예배와 교회 행사의 마음을 사진, 영상, 지도와 신청까지 하나의 초대장에 담아 전합니다.</p><div class="actions"><a class="btn primary" href="<?=View::e($loginUrl)?>"><?=$dashboardUrl?'내 초대장 관리하기':'무료체험 시작하기'?></a><a class="btn secondary" href="#templates">초대장 둘러보기</a></div><small>30일 무료체험 · 카드 등록 없이 시작</small></div>
 <div class="hero-visual hero-image-wrap reveal"><img class="hero-product-image" src="/assets/images/home/invitation-hero.webp" alt="부활절 예배, 성탄절 초청예배, 찬양집회와 지역초청을 표현한 기독교 모바일 초대장 예시" width="1600" height="1067" fetchpriority="high"><div class="float-label top">링크 하나로<br><b>간편하게 공유</b></div><div class="float-label bottom">행사별 디자인을<br><b>한눈에 선택</b></div></div>
</section>
<div class="event-strip"><span>새생명축제</span><i>✦</i><span>특별예배</span><i>✦</i><span>찬양집회</span><i>✦</i><span>수련회</span><i>✦</i><span>지역초청</span></div>

<section class="section templates" id="templates"><div class="heading center reveal"><p class="eyebrow center"><i></i>INVITATION DESIGN<i></i></p><h2>교회의 마음을 담은<br>다양한 초대장을 만나보세요.</h2><p>행사의 성격과 분위기에 맞춰 우리 교회만의 초대장을 완성할 수 있습니다.</p></div><div class="template-rail reveal"><?php foreach($samples as [$type,$title,$color,$en]):?><article class="template-card <?=$color?>"><div><span>✦</span><small><?=View::e($en)?></small></div><section><p><?=View::e($type)?></p><h3><?=View::e($title)?></h3><a href="#features">자세히 보기 →</a></section></article><?php endforeach?></div></section>

<section class="section reasons"><div class="two-column"><div class="heading reveal"><p class="eyebrow"><i></i>WHY CHURCH INVITATION</p><h2>정성껏 준비한 행사,<br>초대하는 과정도<br>따뜻해야 하니까요.</h2><p>복잡한 디자인 도구 없이 교회 담당자가 직접 만들고 수정하도록 필요한 과정만 담았습니다.</p></div><div class="reason-list reveal"><article><b>01</b><div><h3>디자인을 맡길 때마다 부담되셨나요?</h3><p>준비된 구성에서 사진과 글만 바꾸어 직접 완성합니다.</p></div></article><article><b>02</b><div><h3>행사 정보를 여러 번 안내하셨나요?</h3><p>일정, 위치, 영상과 신청을 하나의 주소로 전달합니다.</p></div></article><article><b>03</b><div><h3>신청자 정리가 어려우셨나요?</h3><p>신청자 명단과 참석 상태를 관리자 화면에서 관리합니다.</p></div></article><article><b>04</b><div><h3>처음 온 분에게도 쉬워야 하니까요.</h3><p>설치 없이 열리고 모바일에서 바로 신청할 수 있습니다.</p></div></article></div></div></section>

<section class="section stories" id="features"><div class="heading center reveal"><p class="eyebrow center"><i></i>ALL-IN-ONE<i></i></p><h2>초대의 모든 과정을<br>하나의 흐름으로 이어갑니다.</h2></div>
<article class="story reveal"><div class="story-copy"><span>DESIGN · TEMPLATE</span><h3>행사마다 어울리는<br>기독교 초대장 디자인</h3><p>색상과 사진, 제목을 바꾸어 새생명축제, 절기예배, 집회와 수련회에 맞게 사용하세요.</p><ul><li>세로형·정사각형·가로형 구성</li><li>대표 이미지와 사진 갤러리</li><li>교회명과 행사 정보 중심 편집</li></ul></div><div class="visual feature-photo-wrap"><img class="feature-photo" src="/assets/images/home/community-preparation.webp" alt="교회 공동체가 이웃 초청 행사를 위해 초대장을 함께 준비하는 모습" width="1100" height="825" loading="lazy"></div></article>
<article class="story reverse reveal"><div class="story-copy"><span>SHARE · QR</span><h3>링크와 QR 하나로<br>어디서든 간편하게 공유</h3><p>문자와 메신저는 물론 주보, 포스터와 현수막에도 QR을 넣어 온라인과 현장을 연결합니다.</p><ul><li>공개·비밀번호·비공개 설정</li><li>행사 종료와 만료 관리</li><li>모바일 공유 버튼</li></ul></div><div class="visual feature-photo-wrap"><img class="feature-photo" src="/assets/images/home/youth-welcome.webp" alt="모바일 초대장을 받은 청년을 교회 공동체가 따뜻하게 환영하는 모습" width="1100" height="825" loading="lazy"></div></article>
<article class="story reveal"><div class="story-copy"><span>RSVP · MANAGEMENT</span><h3>참석 신청부터<br>현장 확인까지 한 번에</h3><p>행사에 필요한 질문을 추가하고 신청자 목록, 대기 상태와 출석 여부를 안전하게 관리합니다.</p><ul><li>맞춤 신청 질문</li><li>신청자 CSV 내보내기</li><li>출석·대기 상태 관리</li></ul></div><div class="visual list-visual"><header><span>신청자 현황</span><strong>128<small>명</small></strong></header><?php foreach(['김은혜','박하람','이사랑','최기쁨'] as $i=>$name):?><div><i><?=mb_substr($name,0,1)?></i><span><?=$name?><small><?=$i%2?'참석 확인':'신청 완료'?></small></span><b>확인</b></div><?php endforeach?></div></article></section>

<section class="section steps-wrap" id="steps"><div class="heading center reveal"><p class="eyebrow center"><i></i>EASY START<i></i></p><h2>처음이어도 괜찮아요.<br>네 단계면 초대가 시작됩니다.</h2></div><div class="steps reveal"><article><span>01</span><i>✦</i><h3>단체 정보 입력</h3><p>교회명과 연락처를 등록합니다.</p></article><article><span>02</span><i>▣</i><h3>초대장 만들기</h3><p>행사 정보와 사진을 담습니다.</p></article><article><span>03</span><i>↗</i><h3>링크·QR 공유</h3><p>성도와 이웃에게 전합니다.</p></article><article><span>04</span><i>✓</i><h3>신청자 확인</h3><p>관리 화면에서 현황을 봅니다.</p></article></div></section>

<section class="section functions"><div class="heading center reveal"><p class="eyebrow center"><i></i>BUILT FOR CHURCH<i></i></p><h2>교회 초청에 필요한 기능만<br>정성스럽게 담았습니다.</h2></div><div class="function-grid reveal"><?php foreach($functions as [$n,$name,$desc]):?><article><span><?=$n?></span><h3><?=View::e($name)?></h3><p><?=View::e($desc)?></p></article><?php endforeach?></div></section>

<section class="section pricing" id="pricing"><div class="heading center reveal"><p class="eyebrow center"><i></i>SIMPLE PRICING<i></i></p><h2>부담 없이 시작하고,<br>필요한 만큼 선택하세요.</h2><p>홈페이지 없이 모바일 초대장만 사용할 수 있는 전용 상품입니다.</p></div><div class="plans reveal"><article><span>30일 무료체험</span><h3>체험형</h3><p class="price"><b>0</b>원</p><ul><li>활성 초대장 2개</li><li>관리자 1명</li><li>사진 초대장당 5장</li><li>저장공간 200MB</li></ul><a href="<?=View::e($loginUrl)?>">무료로 시작하기</a></article><article class="recommended"><em>추천</em><span>초대장 기본형</span><h3>기본형</h3><p class="price"><b>4,900</b>원 <small>/월</small></p><ul><li>활성 초대장 5개</li><li>관리자 2명</li><li>사진 초대장당 15장</li><li>저장공간 500MB</li></ul><a href="<?=View::e($loginUrl)?>">기본형 시작하기</a></article><article><span>초대장 성장형</span><h3>성장형</h3><p class="price"><b>9,900</b>원 <small>/월</small></p><ul><li>활성 초대장 20개</li><li>관리자 5명</li><li>사진 초대장당 30장</li><li>저장공간 1.5GB</li></ul><a href="<?=View::e($loginUrl)?>">성장형 시작하기</a></article></div></section>

<section class="final-cta"><span>✦</span><p>INVITE WITH LOVE</p><h2>복음의 기쁜 소식과<br>따뜻한 초대의 마음을 전하세요.</h2><a class="btn dark" href="<?=View::e($loginUrl)?>"><?=$dashboardUrl?'내 초대장 관리하기':'30일 무료로 시작하기'?></a><small>교회의 소중한 만남이 시작되는 곳</small></section>
</main>
<footer><a class="brand" href="/"><b>✦</b><span>Church Invitation</span></a><p>교회와 이웃의 마음을 잇는 기독교 모바일 초대장</p><nav><a href="#features">주요 기능</a><a href="#pricing">요금 안내</a><a href="/login">관리자 로그인</a></nav><small>© <?=date('Y')?> Church Invitation. All rights reserved.</small></footer>
<script>const m=document.querySelector('.menu-toggle'),n=document.querySelector('#main-nav');m?.addEventListener('click',()=>{const o=m.getAttribute('aria-expanded')==='true';m.setAttribute('aria-expanded',String(!o));n?.classList.toggle('open',!o)});n?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m?.setAttribute('aria-expanded','false');n?.classList.remove('open')}));if(matchMedia('(prefers-reduced-motion:reduce)').matches)document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));else{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>o.observe(e))}</script>
