<?php use App\Core\Csrf; use App\Core\View; ?>
<div class="page-header"><div><p class="eyebrow">교회·단체 설정</p><h1>기본정보</h1><p class="muted">초대장과 향후 홈페이지에 공통으로 사용할 정보를 관리합니다.</p></div><a class="button secondary" href="/admin">대시보드</a></div>
<?php if($error): ?><div class="alert alert-error"><?= View::e($error) ?></div><?php endif; ?><?php if($success): ?><div class="alert alert-success"><?= View::e($success) ?></div><?php endif; ?>
<form class="form-grid profile-form" method="post" action="/admin/church"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>">
<section class="panel form-section"><h2>교회 정보</h2><label>교회·단체명 *<input name="name" required maxlength="150" value="<?= View::e($item['name']??'') ?>"></label><label>영문명<input name="english_name" maxlength="150" value="<?= View::e($item['english_name']??'') ?>"></label><label class="full">한 줄 소개<textarea name="short_description" rows="3" maxlength="500"><?= View::e($item['short_description']??'') ?></textarea></label><label>대표자 이름<input name="representative_name" maxlength="100" value="<?= View::e($item['representative_name']??'') ?>"></label><label>대표자 직함<input name="representative_title" maxlength="50" value="<?= View::e($item['representative_title']??'') ?>"></label></section>
<section class="panel form-section"><h2>연락처</h2><label>담당자<input name="contact_name" maxlength="100" value="<?= View::e($item['contact_name']??'') ?>"></label><label>이메일<input type="email" name="contact_email" maxlength="190" value="<?= View::e($item['contact_email']??'') ?>"></label><label>전화번호<input name="contact_phone" maxlength="30" value="<?= View::e($item['contact_phone']??'') ?>"></label></section>
<section class="panel form-section"><h2>주소</h2><label>우편번호<input name="postal_code" maxlength="10" value="<?= View::e($item['postal_code']??'') ?>"></label><label class="full">기본주소<input name="address_line1" maxlength="255" value="<?= View::e($item['address_line1']??'') ?>"></label><label class="full">상세주소<input name="address_detail" maxlength="150" value="<?= View::e($item['address_detail']??'') ?>"></label><label class="full">지도 URL (HTTPS)<input type="url" name="map_url" maxlength="500" value="<?= View::e($item['map_url']??'') ?>"></label></section>
<section class="panel form-section"><h2>웹·SNS 링크</h2><?php foreach(['website_url'=>'홈페이지','youtube_url'=>'유튜브','instagram_url'=>'인스타그램','facebook_url'=>'페이스북'] as $field=>$label): ?><label class="full"><?= $label ?> URL (HTTPS)<input type="url" name="<?= $field ?>" maxlength="500" value="<?= View::e($item[$field]??'') ?>"></label><?php endforeach; ?></section>
<div class="form-actions"><button class="button primary" type="submit">기본정보 저장</button></div></form>
