<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Session;use App\Core\TenantContext;use App\Core\View;use App\Repositories\AuditLogRepository;use App\Repositories\InvitationStatsRepository;use App\Services\SubscriptionEntitlementService;use DateTimeImmutable;use PDO;
final class AnalyticsAdminController{
 public function __construct(private readonly PDO $pdo){}public function index():void{View::render('admin.analytics.index',['title'=>'통합 통계']+$this->report());}
 public function export():void{$d=$this->report();$a=Session::get('auth',[]);(new AuditLogRepository($this->pdo))->record((int)($a['user_id']??0),$d['tenant']->churchId(),'analytics.exported','analytics',null,['from'=>$d['from'],'to'=>$d['to'],'rows'=>count($d['daily'])]);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="invitation-analytics-'.$d['from'].'-'.$d['to'].'.csv"');echo "\xEF\xBB\xBF";$o=fopen('php://output','wb');fputcsv($o,['날짜','조회','공유','신청','트래픽(bytes)']);foreach($d['daily'] as $r)fputcsv($o,[$this->cell((string)$r['stat_date']),(int)$r['views'],(int)$r['shares'],(int)$r['applications'],(int)$r['traffic_bytes']]);fclose($o);exit;}
 private function report():array{$t=TenantContext::fromSession();$e=new SubscriptionEntitlementService($this->pdo);$s=$e->snapshot($t->churchId());$days=max(1,(int)($e->limit($s,'analytics.retention_days')??30));$earliest=(new DateTimeImmutable('today'))->modify('-'.($days-1).' days');$to=$this->date((string)($_GET['to']??''))??new DateTimeImmutable('today');$from=$this->date((string)($_GET['from']??''))??$to->modify('-29 days');if($to>new DateTimeImmutable('today'))$to=new DateTimeImmutable('today');if($from<$earliest)$from=$earliest;if($from>$to)$from=$to;$span=(int)$from->diff($to)->days+1;$pt=$from->modify('-1 day');$pf=$pt->modify('-'.($span-1).' days');if($pf<$earliest)$pf=$earliest;$r=new InvitationStatsRepository($this->pdo);$f=$from->format('Y-m-d');$z=$to->format('Y-m-d');return ['tenant'=>$t,'from'=>$f,'to'=>$z,'earliest'=>$earliest->format('Y-m-d'),'retentionDays'=>$days,'summary'=>$r->aggregateForTenant($t,$f,$z),'previous'=>$r->aggregateForTenant($t,$pf->format('Y-m-d'),$pt->format('Y-m-d')),'daily'=>$r->dailyAggregateForTenant($t,$f,$z,366),'weekly'=>$r->periodAggregateForTenant($t,$f,$z,'week'),'monthly'=>$r->periodAggregateForTenant($t,$f,$z,'month'),'popular'=>$r->popularForTenant($t,$f,$z,20)];}
 private function date(string $v):?DateTimeImmutable{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v?$d:null;}private function cell(string $v):string{return preg_match('/^[=+\-@\t]/',$v)===1?"'".$v:$v;}
}
