<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Csrf;use App\Core\Response;use App\Core\Session;use App\Core\TenantContext;use App\Core\View;use App\Repositories\AuditLogRepository;use App\Repositories\InvitationMediaRepository;use App\Services\SubscriptionEntitlementService;use PDO;
final class MediaAdminController{
 public function __construct(private readonly PDO $pdo){}
 public function index():void{$t=TenantContext::fromSession();$r=new InvitationMediaRepository($this->pdo);$f=['q'=>trim((string)($_GET['q']??'')),'state'=>(string)($_GET['state']??'active'),'size'=>(string)($_GET['size']??'all'),'sort'=>(string)($_GET['sort']??'newest')];$e=new SubscriptionEntitlementService($this->pdo);$s=$e->snapshot($t->churchId());View::render('admin.media.index',['title'=>'사진 관리','items'=>$r->listForTenant($t,$f),'usage'=>$r->storageSummary($t),'limit'=>$e->limit($s,'storage.total_bytes'),'filters'=>$f,'success'=>Session::pullFlash('success'),'error'=>Session::pullFlash('error')]);}
 public function update(int $id):void{Csrf::verify($_POST['_token']??null);$t=TenantContext::fromSession();$alt=trim((string)($_POST['alt_text']??''));if(mb_strlen($alt)>255)$this->fail('대체 텍스트는 255자 이하여야 합니다.');if(!(new InvitationMediaRepository($this->pdo))->updateMetadata($t,$id,$alt,isset($_POST['usage_consent'])))Response::abort(404,'사진을 찾을 수 없습니다.');$this->audit($t,'media.metadata_updated',$id);Session::flash('success','사진 정보를 저장했습니다.');Response::redirect('/admin/media');}
 public function trash(int $id):void{Csrf::verify($_POST['_token']??null);$t=TenantContext::fromSession();if(!(new InvitationMediaRepository($this->pdo))->trash($t,$id,$this->userId()))Response::abort(404,'사진을 찾을 수 없습니다.');$this->audit($t,'media.trashed',$id);Session::flash('success','사진을 휴지통으로 이동했습니다.');Response::redirect('/admin/media');}
 public function restore(int $id):void{Csrf::verify($_POST['_token']??null);$t=TenantContext::fromSession();if(!(new InvitationMediaRepository($this->pdo))->restore($t,$id))Response::abort(404,'사진을 찾을 수 없습니다.');$this->audit($t,'media.restored',$id);Session::flash('success','사진을 복원했습니다.');Response::redirect('/admin/media?state=trash');}
 public function storage():void{$t=TenantContext::fromSession();$r=new InvitationMediaRepository($this->pdo);$e=new SubscriptionEntitlementService($this->pdo);$s=$e->snapshot($t->churchId());View::render('admin.storage.index',['title'=>'저장공간','usage'=>$r->storageSummary($t),'large'=>$r->listForTenant($t,['state'=>'all','size'=>'large','sort'=>'size_desc']),'limit'=>$e->limit($s,'storage.total_bytes')]);}
 private function userId():int{$a=Session::get('auth',[]);return (int)($a['user_id']??0);}private function audit(TenantContext $t,string $a,int $id):void{(new AuditLogRepository($this->pdo))->record($this->userId(),$t->churchId(),$a,'invitation_media',$id);}private function fail(string $m):never{Session::flash('error',$m);Response::redirect('/admin/media');}
}
